<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Vite Manifest Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the path to the Vite manifest file
    | for your application. This file is generated by Vite and contains
    | references to your application's CSS and JavaScript assets.
    |
    */

    'manifest' => public_path('build/manifest.json'),

    /*
    |--------------------------------------------------------------------------
    | Vite Dev Server URL
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URL of the Vite development
    | server. This server handles all requests for assets during local
    | development and injects hot-reloading script into the views.
    |
    */

    'dev_server' => env('VITE_DEV_SERVER', 'http://localhost:3000'),

];
